name: On Push Any Documentation Check
on:   push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run:  |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install -r requirements/requirements_dev.txt
              pip install -r requirements/requirements_docs.txt
      - uses: cnheider/postdoc@master

